name: publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
          scope: '@wundergraph'
      - run: yarn
      - run: yarn set-version
      - run: yarn build
      - run: yarn publish --access public --tags next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
